### Register a user
POST http://localhost:5003/api/auth/register
Content-Type: application/json

{
    "email": "testuser5@gmail.com",
    "password": "testpassword5"
}

### Login a user
POST http://localhost:5003/api/auth/login
Content-Type: application/json  

{
    "email": "testuser3@gmail.com",
    "password": "testpassword3"
}